- hosts: web
  vars_files:
    - vars/web_var.yml
  tasks:
  - name: "Update yum"
    shell: |
      apt update -y
    become: yes

#앱설치
  - name: "Insatll App"
    shell: |
      apt -y install "{{ item }}"
    with_items:
      - "{{ web_apps }}"