- hosts: was
  vars_files:
    - /root/3tir/playbook/vars/was_var.yaml
  tasks:
  - name: "Git Clone"
    shell: |
      git clone https://github.com/woosun/backend.git
    become: yes
  - name: "Install flask server"
    shell: |
      cd ./backend/
      pip install -r ./requirements.txt
    become: yes
#DBCONFIG COPY
  - name: "Copy path file"
    copy:
      src: /root/3tir/playbook/config/env_db_host
      dest: /tmp/env_db_host
    become: yes

  - name: "Copy start_sh file"
    copy:
      src: /root/3tir/playbook/config/was_start.sh
      dest: /home/ubuntu/backend/was_start.sh
    become: yes