- hosts: was
  tasks:
  - name: "Git Clone"
    shell: |
      git clone https://github.com/woosun/backend.git
    become: yes
  - name: "Install flask server"
    shell: |
      cd ./backend/
      pip install -r ./requirements.txt
    become: yes
    register: result
  - debug:
      msg: "{{result}}"

  - name: "Copy start_sh file"
    copy:
      src: /root/3tir/playbook/config/was_start.sh
      dest: /home/ubuntu/backend/was_start.sh
    become: yes