- hosts: web
  tasks:
  - name: "pach "
    copy:
      src: /root/3tir/playbook/config/env_was_host
      dest: /tmp/env_was_host
    become: yes
  - name: "frontend_clone"
    shell: |
      git clone https://github.com/woosun/frontend.git
      cd ./frontend/
      source /tmp/env_was_host
      sudo mv ./frontend.conf /etc/nginx/conf.d/default.conf
      sudo rm /etc/nginx/sites-enabled/default
      sudo sed -i "s/svc-was/$WAS_ADDR/g" /etc/nginx/conf.d/default.conf
      sudo sed -i "s/8080/8000/g" /etc/nginx/conf.d/default.conf
      sudo mkdir /usr/share/nginx/html/static
      sudo mv ./hello.html /usr/share/nginx/html/static/
      sudo sed -i "s/svc-was/$WEB_PUB_ADDR/g" /usr/share/nginx/html/static/hello.html
    become: yes
    register: result  
  - debug:
      msg: "{{result}}"
