- hosts: web
  vars_files:
    - /root/3tir/playbook/vars/env_was_host.yaml
  tasks:
  - name: "nginx config edit"
    shell: |
      export {{WAS_ADDR}}
      export {{WEB_PUB_ADDR}}
      git clone https://github.com/woosun/frontend.git
      cd ./frontend/
      sudo mv ./frontend.conf /etc/nginx/conf.d/default.conf
      sudo rm /etc/nginx/sites-enabled/default
      sudo sed -i "s/svc-was/$WAS_ADDR/g" /etc/nginx/conf.d/default.conf
      sudo sed -i "s/8080/8000/g" /etc/nginx/conf.d/default.conf
      sudo mkdir /usr/share/nginx/html/static
      sudo mv ./hello.html /usr/share/nginx/html/static/
      sudo sed -i "s/svc-was/$WEB_PUB_ADDR/g" /usr/share/nginx/html/static/hello.html
    become: yes
    register: result  
  - debug:
      msg: "{{result}}"
