- hosts: web
  vars_files:
    - /root/3tir/playbook/vars/web_var.yaml
  tasks:
  - name: "apt update repo add"
    shell: |
      apt update -y
    become: yes
  - name: "Insatll App"
    shell: |
      apt -y install "{{ item }}"
    become: yes
    with_items:
      - "{{ web_apps }}"