- hosts: ["192.168.179.120"]
  vars_files:
    - vars/was_install_var.yml
  vars:
    project_path: "yoskr"
  tasks:
  - name: "Replace server.xml file"
    template:
      src: config/server.xml.j2
      dest: /usr/local/tomcat9/conf/server.xml
    become: yes
  - name: "Create Context Dir"
    shell: |
      mkdir /usr/local/tomcat9/webapps/{{ project_path }}
    become: yes

  - name: "Copy jsp file"
    copy:
      src: config/test.jsp
      dest: /usr/local/tomcat9/webapps/{{ project_path }}/test.jsp
    become: yes

  - name: "Download mysql-connector"
    shell: |
      wget -O /tmp/{{ mysql-connector_var }}.tar.gz https://dev.mysql.com/get/Downloads/Connector-J/{{ mysql-connector_var }}.tar.gz
    become: yes

  - name: "Unarchive mysql-connector"
    unarchive:
      src: "/tmp/{{ mysql-connector_var }}.tar.gz"
      dest: "/tmp"
      remote_src: True
    become: yes

  - name: "Copy mysql-connector"
    shell: |
      cp /tmp/{{ mysql-connector_var }}/*.jar /usr/local/tomcat9/lib/
    become: yes